apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
    tags.datadoghq.com/env: {{ .Values.frontend.datadog.env | quote }}
    tags.datadoghq.com/service: {{ .Values.frontend.datadog.service | quote }}
    tags.datadoghq.com/version: {{ .Values.global.version | quote }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        tags.datadoghq.com/env: {{ .Values.frontend.datadog.env | quote }}
        tags.datadoghq.com/service: {{ .Values.frontend.datadog.service | quote }}
        tags.datadoghq.com/version: {{ .Values.global.version | quote }}
        admission.datadoghq.com/enabled: {{ .Values.frontend.datadog.enabled | quote }}
      annotations:
        admission.datadoghq.com/js-lib.version: {{ .Values.frontend.datadog.jsLibVersion | quote }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
          name: http
        env:
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: {{ .Values.frontend.datadog.logsInjection | quote }}
        - name: DD_RUNTIME_METRICS_ENABLED
          value: {{ .Values.frontend.datadog.runtimeMetricsEnabled | quote }}
        - name: DD_TRACE_ANALYTICS_ENABLED
          value: {{ .Values.frontend.datadog.traceAnalyticsEnabled | quote }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
